#pragma once
class OrganStops
{
public:
	OrganStops();
	~OrganStops();

	bool Pedal_FestivalTrumpet8 = false;
	bool Pedal_Fagot16 = false;
	bool Pedal_FournitureIV = false; 
	bool Pedal_ChoralBass4 = false;
	bool Pedal_Octave8 = false;
	bool Pedal_Geigen16 = false;
	bool Pedal_Principal16 = false;
	bool Pedal_ContraBeigen32 = false;
	bool Pedal_Klarine4 = false;
	bool Pedal_Trompete8 = false;
	bool Pedal_Posaune16 = false;
	bool Pedal_HarleyDavidson32 = false;
	bool Pedal_Geigen8 = false;
	bool Pedal_ContraViola16 = false;
	bool Pedal_ContraBass16 = false;
	bool Pedal_EnglishHorn4 = false;
	bool Pedal_Trompette8 = false;
	bool Pedal_Bombarde16 = false;
	bool Pedal_RohrFlute4 = false;
	bool Pedal_Bourdon8 = false;
	bool Pedal_SubBass16 = false;
	bool Pedal_MolzGedeckt16 = false;
	bool Pedal_Resultant32 = false;
	
	bool Swell_SwellUnison = false;
	bool Swell_FestivalTrumpet8 = false;
	bool Swell_Trompette8 = false;
	bool Swell_PleinJeuIII_IV = false;
	bool Swell_Octavin2 = false;
	bool Swell_Principal4 = false;
	bool Swell_GeigenPrincipal8 = false;
	bool Swell_ContraViole16 = false;
	bool Swell_Swell4 = false;
	bool Swell_Swell16 = false;
	bool Swell_Clairon4 = false;
	bool Swell_Bombarde16 = false;
	bool Swell_Tierce1_3_5 = false;
	bool Swell_Hazard2_2_3 = false;
	bool Swell_Nachthorn4 = false;
	bool Swell_WaldFlute8 = false;
	bool Swell_Tremolo = false;
	bool Swell_Oboe8 = false;
	bool Swell_VoxHumana8 = false;
	bool Swell_FluteCeleste8 = false;
	bool Swell_FlautoDolce8 = false;
	bool Swell_VioleCeleste8 = false;
	bool Swell_Viole = false;

	bool Solo_Solo4 = false;
	bool Solo_Solo16 = false;
	bool Solo_SoloTremolo = false;
	bool Solo_EnglishHorn8 = false;
	bool Solo_ViolonCelloCeleste8 = false;
	bool Solo_ViolonCello8 = false;
	bool Solo_SoloUnison = false;
	bool Solo_FestivalTrumpet8 = false;
	bool Solo_HarmonicClairon4 = false;
	bool Solo_HarmonicTrumpet8 = false;
	bool Solo_FrenchHorn8 = false;
	bool Solo_Chimes = false;
	bool Solo_TibiaTremolo = false;
	bool Solo_Tibia1_3_5 = false;
	bool Solo_Tibia2 = false;
	bool Solo_Tibia2_2_3 = false;
	bool Solo_Tibia4 = false;
	bool Solo_Tibia8 = false;


	bool Great_GreatUnison = false;
	bool Great_FestivalTrumpet8 = false;
	bool Great_Fagot16 = false;
	bool Great_RohrFlute4 = false;
	bool Great_Bourdon8 = false;
	bool Great_ViolonCelloCeleste8 = false;
	bool Great_ViolonCello8 = false;
	bool Great_Great4 = false;
	bool Great_Great16 = false;
	bool Great_Trompete8 = false;
	bool Great_CornetII = false;
	bool Great_HarmonicFlute4 = false;
	bool Great_HarmonicFlute8 = false;
	bool Great_Geigan8 = false;
	bool Great_Tremolo = false;
	bool Great_ScharfIV = false;
	bool Great_FournitureIV = false;
	bool Great_SuperOctave2 = false;
	bool Great_Octave4 = false;
	bool Great_Principal8 = false;
	bool Great_Gaigen16 = false;

	bool Choir_Tremolo = false;
	bool Choir_Tibia4 = false;
	bool Choir_Tibia8 = false;
	bool Choir_UndaMaris8 = false;
	bool Choir_Dulciana8 = false;
	bool Choir_ViolaCeleste8 = false;
	bool Choir_ViolaPomposa8 = false;
	bool Choir_ChoirUnison = false;
	bool Choir_FestivalTrumpet8 = false;
	bool Choir_Clarinet8 = false;
	bool Choir_BlockFlute2 = false;
	bool Choir_KoppelFlute4 = false;
	bool Choir_ConcertFlute8 = false;
	bool Choir_Holzgedeckt16 = false;
	bool Choir_Choir4 = false;
	bool Choir_Choir16 = false;
	bool Choir_Cymbel4 = false;
	bool Choir_Larigot1_1_2 = false;
	bool Choir_Principal2 = false;
	bool Choir_Spitzgeigen4 = false;
	bool Choir_Choir_Holzgedeckt8 = false;
};

